// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldZArUbyi92q-GKedUulc9HVYxeI3Dqo',
    appId: '1:658892135437:web:12f7e4ec3a719c5576c944',
    messagingSenderId: '658892135437',
    projectId: 'flutter-student-app-b9106',
    authDomain: 'flutter-student-app-b9106.firebaseapp.com',
    storageBucket: 'flutter-student-app-b9106.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIX-xaERdkjFUqxQC711da0WEPfYnbB20',
    appId: '1:658892135437:android:d3695a893135846576c944',
    messagingSenderId: '658892135437',
    projectId: 'flutter-student-app-b9106',
    storageBucket: 'flutter-student-app-b9106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-F8J731kpaObNw_KTaSJJUSDTXeqgBs',
    appId: '1:658892135437:ios:00a27b738fe19ba676c944',
    messagingSenderId: '658892135437',
    projectId: 'flutter-student-app-b9106',
    storageBucket: 'flutter-student-app-b9106.firebasestorage.app',
    iosBundleId: 'com.example.firebaseStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM-F8J731kpaObNw_KTaSJJUSDTXeqgBs',
    appId: '1:658892135437:ios:00a27b738fe19ba676c944',
    messagingSenderId: '658892135437',
    projectId: 'flutter-student-app-b9106',
    storageBucket: 'flutter-student-app-b9106.firebasestorage.app',
    iosBundleId: 'com.example.firebaseStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDldZArUbyi92q-GKedUulc9HVYxeI3Dqo',
    appId: '1:658892135437:web:a76cc30da38e0fe476c944',
    messagingSenderId: '658892135437',
    projectId: 'flutter-student-app-b9106',
    authDomain: 'flutter-student-app-b9106.firebaseapp.com',
    storageBucket: 'flutter-student-app-b9106.firebasestorage.app',
  );
}
